repos:
  - repo: local
    hooks:
      - id: block-triple-q
        name: block-triple-q (deny "??? in added lines")
        language: system
        pass_filenames: false
        stages: [commit]
        # НЕ проверяем сам конфиг pre-commit
        files: '^(?!\.pre-commit-config\.yaml$).*'
        entry: python
        args:
          - -c
          - |
            import re, subprocess, sys
            # staged diff только по репозиторию, исключая сам конфиг
            cmd = ["git","diff","--cached","-U0","--",".",":!.pre-commit-config.yaml"]
            out = subprocess.run(cmd, capture_output=True, text=True).stdout
            bad = [ln for ln in out.splitlines() if re.match(r"^\+.*\?{3,}", ln)]
            if bad:
                print("⛔ Found triple-question marks in added lines:\n")
                print("\n".join(bad))
                print("\nTip: git diff --cached -U0 -- <file> | grep -nE '^\\+.*\\?{3,}'")
                sys.exit(1)
