# docker-compose.backend.yml
#version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hr_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://hruser:hrpassword@host.docker.internal:5432/hrdb  # Для Windows
      OPENAI_API_KEY: ${OPENAI_API_KEY:-sk-dummy-key-for-testing}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-this}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для доступа к postgres на хосте