# docker-compose.yml - упрощенная версия для отладки
version: '3.8'
services:
  postgres:
    image: docker.io/bitnami/postgresql:17
    container_name: hr_postgres
    environment:
      # Эти переменные создадут пользователя и БД автоматически
      POSTGRES_USER: hruser
      POSTGRES_PASSWORD: hrpassword
      POSTGRES_DB: hrdb
      # Разрешаем подключения без пароля для отладки
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      # Правильная проверка - указываем базу hrdb
      test: ["CMD-SHELL", "pg_isready -U hruser -d hrdb || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  llm_agent:
    image: llm_agent:1
    container_name: llm_agent
    build: ./llm_agent
    restart: always

  frontend:
    image: frontend:1
    container_name: frontend
    build: ./frontend
    ports:
      - "5000:5000"
    restart: always

  db_backend:
    image: db_backend:1
    container_name: db_backend
    build: ./db_backend
    restart: always


volumes:
  postgres_data:
    driver: local