version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: hr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hrdb
      POSTGRES_USER: hruser
      POSTGRES_PASSWORD: hrpassword
    ports:
      - "5432:5432" # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hruser -d hrdb"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
